name: "${project.name}"
version: "${project.version}"
main: "${project.groupId}.Main"
author: 'erudo'
api-version: 1.13
depend: [Multiverse-Core,Multiverse-Portals]
commands:
    emw:
      description: EMine-World command